<?php

/**
 * @file
 * Contains switches.module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\switches\Entity\SwitchEntity;

/**
 * Implements hook_entity_access().
 */
function switches_additions_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = func_get_args();
  return $feature_flag_manager->invokeAccessFunctionForPlugins('entityAccess', $args);
}

/**
 * Implements hook_entity_create_access().
 */
function switches_additions_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = func_get_args();
  return $feature_flag_manager->invokeAccessFunctionForPlugins('entityCreateAccess', $args);
}

/**
 * Implements hook_form_FORM_ID_alter() for \Drupal\recommender\Form\RecommendationAdminSettingsForm.
 */
function switches_additions_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = [&$form, $form_state, $form_id];
  $feature_flag_manager->invokeFunctionForPlugins('formAlter', $args);
}

/**
 * Implements hook_switches_perls_adaptive_content_adaptive_content_info_alter().
 */
function switches_additions_perls_adaptive_content_adaptive_content_info_alter(array &$re_info) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = [&$re_info];
  $feature_flag_manager->invokeFunctionForPlugins('testInfoAlter', $args);
}

/**
 * Implements hook_switches_recommender_engine_info_alter().
 */
function switches_additions_recommender_engine_info_alter(array &$re_info) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = [&$re_info];
  $feature_flag_manager->invokeFunctionForPlugins('infoAlter', $args);
}

/**
 * Implements hook_switches_badge_info_alter().
 */
function switches_additions_badge_info_alter(array &$re_info) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = [&$re_info];
  $feature_flag_manager->invokeFunctionForPlugins('achievementInfoAlter', $args);
}

/**
 * Implements hook_entity_view().
 */
function switches_additions_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = [&$build, $entity, $display, $view_mode];
  $feature_flag_manager->invokeFunctionForPlugins('entityView', $args);
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function switches_additions_field_widget_form_alter(&$element, FormStateInterface &$form_state, $context) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $args = [&$element, &$form_state, $context];
  $feature_flag_manager->invokeFunctionForPlugins('fieldWidgetFormAlter', $args);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function switches_additions_switch_update(SwitchEntity $switch) {
  $feature_flag_manager = \Drupal::service('plugin.manager.switches_additions.feature_flag');
  $feature_flag_manager->switchWasToggled($switch);
}
