<?php

/**
 * @file
 * Module related hooks.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_nodes().
 */
function perls_adaptive_content_preprocess_node(&$variables) {
  // Get current node and associated category url.
  $node = Drupal::routeMatch()->getParameter('node');
  if (empty($node)) {
    $node = $variables['node'];
  }
  if (($node instanceof NodeInterface) &&
    $node->bundle() === 'course' &&
    $variables['view_mode'] === 'full') {
    $variables['#attached']['library'][] = 'perls_adaptive_content/perls_adaptive_content.refresh_course';
  }
}
