<?php

/**
 * @file
 * Contains notifications_badges.module.
 */

use Drupal\achievements\Entity\AchievementEntity;
use Drupal\user\Entity\User;

/**
 * Implements hook_achievements_unlocked().
 */
function badges_xapi_reporting_achievements_unlocked(AchievementEntity $achievement, $user_id) {
  if (is_null($user_id)) {
    return;
  }
  $user = User::load($user_id);
  if (perls_xapi_reporting_user_needs_report($user)) {
    /** @var \Drupal\perls_learner_state\Plugin\XapiStateManager $state_manager */
    $state_manager = \Drupal::service('plugin.manager.state_manager');
    $earned_xapi = $state_manager->createInstance('xapi_achievement_awarded_state');
    $earned_xapi->getReadyStatement($achievement, \Drupal::time()->getCurrentTime(), $user);
    $earned_xapi->sendStatement($user->id());
  }

}

/**
 * Implements hook_preprocess_achievements().
 */
function badges_xapi_reporting_preprocess_achievement(&$variables) {
  $variables['#attached']['library'][] = 'badges_xapi_reporting/badges_xapi_reporting';
}
